var dialsArray = [
  [
    "https://yandex.ru",
    "Яндекс",
    "url(images/Tiles/yandex.png)",
    "md"
  ],
  [
    "https://yandex.ru/maps",
    "Яндекс.Карты",
    "url(images/Tiles/yandex_maps.png)",
    "md"
  ],
  [
    "https://music.yandex.ru",
    "Яндекс.Музыка",
    "url(images/Tiles/yandex_music.png)",
    "md"
  ],
  [
    "https://google.ru",
    "Google",
    "url(images/Tiles/google.png)",
    "md"
  ],
  [
    "https://translate.google.ru",
    "GoogleTranslate",
    "url(images/Tiles/google_translate.png)",
    "sm"
  ],
  [
    "https://youtube.com",
    "YouTube",
    "url(images/Tiles/youtube.png)",
    "md"
  ],
  [
    "https://vkvideo.ru/",
    "VK Video",
    "url(images/Tiles/VKvideo.png)",
    "bg"
  ],
  [
    "https://keep.google.com",
    "GoogleKeep",
    "url(images/Tiles/google_keep.png)",
    "bg"
  ],
  [
    "https://vk.com",
    "Вконтакте",
    "url(images/Tiles/vk.png)",
    "bg"
  ],
  [
    "https://www.tinkoff.ru/mybank/",
    "Tinkoff",
    "url(images/Tiles/tinkoff.png)",
    "bg"
  ],
  [
    "https://e.mail.ru/inbox/",
    "Mail.ru",
    "url(images/Tiles/mailru.png)",
    "bg"
  ],
  [
    "https://pikabu.ru",
    "Пикабу",
    "url(images/Tiles/pikabu.png)",
    "bg"
  ],
  [
    "https://instagram.com",
    "Instagram",
    "url(images/Tiles/instagram.png)",
    "bg"
  ],
  [
    "https://console.yandex.cloud/folders/b1gtqi4firkqkvl9sofd/foundation-models/chat",
    "Yandex.GPT3",
    "url(images/Tiles/Yandex_GPT.png)",
    "md"
  ],
  [
    "https://store.steampowered.com",
    "Steam",
    "url(images/Tiles/steam.png)",
    "bg"
  ],
  [
    "https://www.dns-shop.ru",
    "DNS",
    "url(images/Tiles/dns.png)",
    "bg"
  ],
  [
    "https://market.yandex.ru",
    "Яндекс.Маркет",
    "url(images/Tiles/yandex_market.png)",
    "bg"
  ],
  [
    "https://www.wildberries.ru",
    "Wildberries",
    "url(images/Tiles/wildberries.png)",
    "bg"
  ],
  [
    "https://www.ozon.ru/",
    "Ozon",
    "url(images/Tiles/ozon.png)",
    "bg"
  ],
  [
    "https://ru.aliexpress.com",
    "AliExpress",
    "url(images/Tiles/aliexpress.png)",
    "bg"
  ],
  [
    "https://lingualeo.com",
    "Lingualeo",
    "url(images/Tiles/lingualeo.png)",
    "bg"
  ],
  [
    "https://github.com/MaxMukovin",
    "GitHub",
    "url(images/Tiles/github.png)",
    "md"
  ],
  [
    "https://speedtest.net",
    "SpeedTest",
    "url(images/Tiles/speedtest.png)",
    "bg"
  ],
  [
    "https://app.todoist.com/",
    "Todoist",
    "url(images/Tiles/todoist.png)",
    "bg"
  ],
  [
    "https://miro.com/app/dashboard",
    "Miro",
    "url(images/Tiles/miro.png)",
    "bg"
  ],
  [
    "https://www.litres.ru",
    "ЛитРес",
    "url(images/Tiles/Litres.png)",
    "bg"
  ],
  [
    "http://ringostarrr.ru:32400",
    "Plex",
    "url(images/Tiles/plex.png)",
    "bg"
  ],
  [
    "https://www.avito.ru",
    "Avito",
    "url(images/Tiles/avito.png)",
    "bg"
  ],
  [
    "https://dev.rightech.io/",
    "Rightech.io",
    "url(images/Tiles/rightech.png)",
    "bg"
  ],
  [
    "https://ib.online.gpb.ru/",
    "Газпромбанк",
    "url(images/Tiles/gazprombank.png)",
    "bg"
  ],
  [
    "https://client.blurams.com/device/list",
    "Blurams",
    "url(images/Tiles/blurams.png)",
    "bg"
  ],
  [
    "http://indexrs.h1n.ru",
    "SandBox",
    "url(images/Tiles/sandbox.png)",
    "bg"
  ],
  [
    "https://disk.yandex.ru/",
    "Яндекс.Диск",
    "url(images/Tiles/YandexDisk.png)",
    "md"
  ],
  [
    "https://cloud.mail.ru/public/Ag2B/pDs4kFJrz",
    "CloudMail",
    "url(images/Tiles/CloudMail.png)",
    "bg"
  ],
  [
    "../indexAIDA.html",
    "AIDA64 Monitor",
    "url(images/Tiles/AIDA64.png)",
    "bg"
  ],
]